
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author up772320
 */
public class mainMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    
    ResultSet rs;
    int curRow = 0;
    String userID;
    
    String authorisation;
    
    /**
     *
     * @param tempID temporarily holds the user ID until moved to a global variable
     * @throws SQLException will identify an SQL error if/when one occurs
     */
    public mainMenuAdmin( String tempID) throws SQLException {
                
        userID = tempID;
        authorisation = "a";
        
        initComponents();
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogOut = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnUserScreen = new javax.swing.JButton();
        btnRoomScreen = new javax.swing.JButton();
        btnEditRooms = new javax.swing.JButton();
        btnUserScreen1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking system");

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Main menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnUserScreen.setText("View users");
        btnUserScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserScreenActionPerformed(evt);
            }
        });

        btnRoomScreen.setText("Make booking");
        btnRoomScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomScreenActionPerformed(evt);
            }
        });

        btnEditRooms.setText("Edit Rooms");
        btnEditRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRoomsActionPerformed(evt);
            }
        });

        btnUserScreen1.setText("My bookings");
        btnUserScreen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserScreen1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUserScreen)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEditRooms))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnRoomScreen)
                        .addGap(18, 18, 18)
                        .addComponent(btnUserScreen1))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoomScreen)
                    .addComponent(btnUserScreen)
                    .addComponent(btnUserScreen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditRooms)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(btnLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserScreenActionPerformed

        this.dispose();
        
        try {
            new adminScreen(userID).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnUserScreenActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        try {
            new loginScreen().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
         this.dispose();

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnRoomScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomScreenActionPerformed

        try {
            new bookingScreen(userID, authorisation).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
        
        
    }//GEN-LAST:event_btnRoomScreenActionPerformed

    private void btnUserScreen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserScreen1ActionPerformed

        try {
            new myBookings(userID, authorisation).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUserScreen1ActionPerformed

    private void btnEditRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRoomsActionPerformed
        
        try {
            new roomsScreen(userID).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        
    }//GEN-LAST:event_btnEditRoomsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditRooms;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRoomScreen;
    private javax.swing.JButton btnUserScreen;
    private javax.swing.JButton btnUserScreen1;
    private javax.swing.JPanel jPanel11;
    // End of variables declaration//GEN-END:variables
}
